// This file was generated by gloss
// https://github.com/abs0luty/gloss
//
// Do not modify this file directly.
// Any changes will be overwritten when gloss regenerates this file.

import example.{
  type Message, type Product, type Status, type User, type Voice, Active, Image,
  Inactive, Pending, Product, Text, User, Video, Voice,
}
import gleam/dynamic/decode
import gleam/option

pub fn voice_decoder() -> decode.Decoder(Voice) {
  use mime_type <- decode.optional_field(
    "mime_type",
    option.None,
    decode.optional(decode.string),
  )
  use file_size <- decode.field("file_size", decode.optional(decode.int))
  decode.success(Voice(mime_type:, file_size:))
}

pub fn user_decoder() -> decode.Decoder(User) {
  use user_name <- decode.field("userName", decode.string)
  use user_age <- decode.field("userAge", decode.int)
  use user_email <- decode.optional_field(
    "userEmail",
    option.None,
    decode.optional(decode.string),
  )
  decode.success(User(user_name:, user_age:, user_email:))
}

pub fn status_decoder() -> decode.Decoder(Status) {
  use variant <- decode.then(decode.string)
  case variant {
    "active" -> {
      decode.success(Active)
    }
    "inactive" -> {
      decode.success(Inactive)
    }
    "pending" -> {
      decode.success(Pending)
    }
    _ -> decode.failure(Active, "one of active, inactive, pending")
  }
}

pub fn message_decoder() -> decode.Decoder(Message) {
  use variant <- decode.field("kind", decode.string)
  case variant {
    "text" -> {
      use content <- decode.field("content", decode.string)
      decode.success(Text(content:))
    }
    "image" -> {
      use url <- decode.field("url", decode.string)
      use width <- decode.field("width", decode.int)
      use height <- decode.field("height", decode.int)
      decode.success(Image(url:, width:, height:))
    }
    "video" -> {
      use url <- decode.field("url", decode.string)
      use duration <- decode.field("duration", decode.int)
      decode.success(Video(url:, duration:))
    }
    _ -> decode.failure(Text(content: ""), "one of image, text, video")
  }
}

pub fn product_decoder() -> decode.Decoder(Product) {
  use name <- decode.field("productName", decode.string)
  use price <- decode.field("productPrice", decode.float)
  decode.success(Product(name:, price:))
}
