// This file was generated by gloss
// https://github.com/abs0luty/gloss
//
// Do not modify this file directly.
// Any changes will be overwritten when gloss regenerates this file.

import example.{
  type Message, type Product, type Status, type User, type Voice, Active, Image,
  Inactive, Pending, Product, Text, User, Video, Voice,
}
import gleam/json

pub fn voice_to_json(voice: Voice) -> json.Json {
  let Voice(mime_type:, file_size:) = voice
  json.object([
    #("mime_type", json.nullable(mime_type, _)),
    #("file_size", json.nullable(file_size, _)),
  ])
}

pub fn user_to_json(user: User) -> json.Json {
  let User(user_name:, user_age:, user_email:) = user
  json.object([
    #("userName", json.string(user_name)),
    #("userAge", json.int(user_age)),
    #("userEmail", json.nullable(user_email, _)),
  ])
}

pub fn status_to_json(status: Status) -> json.Json {
  case status {
    Active -> json.string("active")
    Inactive -> json.string("inactive")
    Pending -> json.string("pending")
  }
}

pub fn message_to_json(message: Message) -> json.Json {
  case message {
    Text(content:) ->
      json.object([
        #("kind", json.string("text")),
        #("content", json.string(content)),
      ])
    Image(url:, width:, height:) ->
      json.object([
        #("kind", json.string("image")),
        #("url", json.string(url)),
        #("width", json.int(width)),
        #("height", json.int(height)),
      ])
    Video(url:, duration:) ->
      json.object([
        #("kind", json.string("video")),
        #("url", json.string(url)),
        #("duration", json.int(duration)),
      ])
  }
}

pub fn product_to_json(product: Product) -> json.Json {
  let Product(name:, price:) = product
  json.object([
    #("productName", json.string(name)),
    #("productPrice", json.float(price)),
  ])
}
